name: ThriveBody
options:
  minimumXcodeGenVersion: 2.41.0
  configFiles:
    Debug: Configs/Debug.xcconfig
    Release: Configs/Release.xcconfig
fileGroups:
  - App/Sources
  - App/Resources
targetTemplates:
  BaseAppTarget:
    platform: iOS
    deploymentTarget: '17.0'
    type: application
    configFiles:
      Debug: Configs/Debug.xcconfig
      Release: Configs/Release.xcconfig
packages:
  LibraryBase:
    path: Packages/Library/Base
  LibraryServiceLoader:
    path: Packages/Library/ServiceLoader
  LibraryThemeKit:
    path: Packages/Library/ThemeKit
  LibraryNetworking:
    path: Packages/Library/Networking
  LibraryNotification:
    path: Packages/Library/Notification
  LibraryTrack:
    path: Packages/Library/Track
  LibraryChatUI:
    path: Packages/Library/ChatUI
  DomainHealth:
    path: Packages/Domain/Health
  DomainAuth:
    path: Packages/Domain/DomainAuth
  DomainChat:
    path: Packages/Domain/DomainChat
  DomainOnboarding:
    path: Packages/Domain/Onboarding
  FeatureHealthKitApi:
    path: Packages/Feature/HealthKit/FeatureHealthKitApi
  FeatureHealthKitImpl:
    path: Packages/Feature/HealthKit/FeatureHealthKitImpl
  FeatureAccountApi:
    path: Packages/Feature/FeatureAccount/FeatureAccountApi
  FeatureAccountImpl:
    path: Packages/Feature/FeatureAccount/FeatureAccountImpl
  FeatureChatApi:
    path: Packages/Feature/FeatureChat/FeatureChatApi
  FeatureChatImpl:
    path: Packages/Feature/FeatureChat/FeatureChatImpl
  FeatureOnboardingApi:
    path: Packages/Feature/Onboarding/FeatureOnboardingApi
  FeatureOnboardingImpl:
    path: Packages/Feature/Onboarding/FeatureOnboardingImpl
  FeatureDebugToolsApi:
    path: Packages/Feature/DebugTools/FeatureDebugToolsApi
  FeatureDebugToolsImpl:
    path: Packages/Feature/DebugTools/FeatureDebugToolsImpl
  FeatureAgendaApi:
    path: Packages/Feature/Agenda/FeatureAgendaApi
  FeatureAgendaImpl:
    path: Packages/Feature/Agenda/FeatureAgendaImpl
targets:
  ThriveBody:
    templates: [BaseAppTarget]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.hehigh.thrivebody
      CODE_SIGN_ENTITLEMENTS: App/ThriveBody.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_FILE: App/Resources/Info.plist
      GENERATE_INFOPLIST_FILE: NO
    sources:
      - path: App/Sources
      - path: App/Resources/Assets.xcassets
        buildPhase: resources
      - path: App/Resources/en.lproj
        buildPhase: resources
      - path: App/Resources/LaunchScreen.storyboard
        buildPhase: resources
    resources: []
    dependencies:
      - package: LibraryBase
        product: LibraryBase
      - package: LibraryServiceLoader
        product: LibraryServiceLoader
      - package: LibraryThemeKit
        product: ThemeKit
      - package: LibraryNetworking
        product: LibraryNetworking
      - package: LibraryNotification
        product: LibraryNotification
      - package: LibraryTrack
        product: LibraryTrack
      - package: LibraryChatUI
        product: LibraryChatUI
      - package: DomainHealth
        product: DomainHealth
      - package: DomainAuth
        product: DomainAuth
      - package: DomainChat
        product: DomainChat
      - package: DomainOnboarding
        product: DomainOnboarding
      - package: FeatureHealthKitApi
        product: FeatureHealthKitApi
      - package: FeatureHealthKitImpl
        product: FeatureHealthKitImpl
      - package: FeatureAccountApi
        product: FeatureAccountApi
      - package: FeatureAccountImpl
        product: FeatureAccountImpl
      - package: FeatureChatApi
        product: FeatureChatApi
      - package: FeatureChatImpl
        product: FeatureChatImpl
      - package: FeatureOnboardingApi
        product: FeatureOnboardingApi
      - package: FeatureOnboardingImpl
        product: FeatureOnboardingImpl
      - package: FeatureDebugToolsApi
        product: FeatureDebugToolsApi
      - package: FeatureDebugToolsImpl
        product: FeatureDebugToolsImpl
      - package: FeatureAgendaApi
        product: FeatureAgendaApi
      - package: FeatureAgendaImpl
        product: FeatureAgendaImpl
      - target: AgendaWidget
        embed: true
  AgendaWidget:
    platform: iOS
    deploymentTarget: '17.0'
    type: app-extension
    configFiles:
      Debug: Configs/Debug.xcconfig
      Release: Configs/Release.xcconfig
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.hehigh.thrivebody.AgendaWidget
      CODE_SIGN_ENTITLEMENTS: AgendaWidget/AgendaWidget.entitlements
      INFOPLIST_FILE: AgendaWidget/Info.plist
      GENERATE_INFOPLIST_FILE: NO
    sources:
      - path: AgendaWidget
    dependencies:
      - package: LibraryBase
        product: LibraryBase
      - package: LibraryNotification
        product: LibraryNotification
schemes:
  ThriveBody:
    build:
      targets:
        ThriveBody: all
        AgendaWidget: all
    run:
      config: Debug
      executable: ThriveBody
    test:
      config: Debug
    archive:
      config: Release
    management:
      shared: true