name: ThriveBody
options:
  minimumXcodeGenVersion: 2.41.0
  configFiles:
    Debug: Configs/Debug.xcconfig
    Release: Configs/Release.xcconfig
    AdHoc: Configs/AdHoc.xcconfig
fileGroups:
  - App/Sources
  - App/Resources
targetTemplates:
  BaseAppTarget:
    platform: iOS
    deploymentTarget: '17.0'
    type: application
    configFiles:
      Debug: Configs/Debug.xcconfig
      Release: Configs/Release.xcconfig
      AdHoc: Configs/AdHoc.xcconfig
packages:
  LibraryServiceLoader:
    path: Packages/Library/ServiceLoader
  LibraryThemeKit:
    path: Packages/Library/ThemeKit
  LibraryNetworking:
    path: Packages/Library/Networking
  LibraryChatUI:
    path: Packages/Library/ChatUI
  DomainHealth:
    path: Packages/Domain/Health
  DomainAuth:
    path: Packages/Domain/DomainAuth
  DomainChat:
    path: Packages/Domain/DomainChat
  DomainOnboarding:
    path: Packages/Domain/Onboarding
  FeatureHealthKitApi:
    path: Packages/Feature/HealthKit/FeatureHealthKitApi
  FeatureHealthKitImpl:
    path: Packages/Feature/HealthKit/FeatureHealthKitImpl
  FeatureAccountApi:
    path: Packages/Feature/FeatureAccount/FeatureAccountApi
  FeatureAccountImpl:
    path: Packages/Feature/FeatureAccount/FeatureAccountImpl
  FeatureChatApi:
    path: Packages/Feature/FeatureChat/FeatureChatApi
  FeatureChatImpl:
    path: Packages/Feature/FeatureChat/FeatureChatImpl
  FeatureOnboardingApi:
    path: Packages/Feature/Onboarding/FeatureOnboardingApi
  FeatureOnboardingImpl:
    path: Packages/Feature/Onboarding/FeatureOnboardingImpl
  FeatureDebugToolsApi:
    path: Packages/Feature/DebugTools/FeatureDebugToolsApi
  FeatureDebugToolsImpl:
    path: Packages/Feature/DebugTools/FeatureDebugToolsImpl
targets:
  ThriveBody:
    templates: [BaseAppTarget]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hehigh.thrivebody
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: App/Resources/Info.plist
        GENERATE_INFOPLIST_FILE: NO
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: App/ThriveBody-Debug.entitlements
        Release:
          CODE_SIGN_ENTITLEMENTS: App/ThriveBody-Release.entitlements
        AdHoc:
          CODE_SIGN_ENTITLEMENTS: App/ThriveBody-Debug.entitlements
    sources:
      - path: App/Sources
      - path: App/Resources/Assets.xcassets
        buildPhase: resources
      - path: App/Resources/en.lproj
        buildPhase: resources
      - path: App/Resources/LaunchScreen.storyboard
        buildPhase: resources
    resources: []
    dependencies:
      - package: LibraryServiceLoader
        product: LibraryServiceLoader
      - package: LibraryThemeKit
        product: ThemeKit
      - package: LibraryNetworking
        product: LibraryNetworking
      - package: LibraryChatUI
        product: LibraryChatUI
      - package: DomainHealth
        product: DomainHealth
      - package: DomainAuth
        product: DomainAuth
      - package: DomainChat
        product: DomainChat
      - package: DomainOnboarding
        product: DomainOnboarding
      - package: FeatureHealthKitApi
        product: FeatureHealthKitApi
      - package: FeatureHealthKitImpl
        product: FeatureHealthKitImpl
      - package: FeatureAccountApi
        product: FeatureAccountApi
      - package: FeatureAccountImpl
        product: FeatureAccountImpl
      - package: FeatureChatApi
        product: FeatureChatApi
      - package: FeatureChatImpl
        product: FeatureChatImpl
      - package: FeatureOnboardingApi
        product: FeatureOnboardingApi
      - package: FeatureOnboardingImpl
        product: FeatureOnboardingImpl
      - package: FeatureDebugToolsApi
        product: FeatureDebugToolsApi
      - package: FeatureDebugToolsImpl
        product: FeatureDebugToolsImpl
schemes:
  ThriveBody:
    build:
      targets:
        ThriveBody: all
    run:
      config: Debug
    archive:
      config: Release
  ThriveBody-AdHoc:
    build:
      targets:
        ThriveBody: all
    run:
      config: AdHoc
    archive:
      config: AdHoc
