name: HealthBuddy
options:
  minimumXcodeGenVersion: 2.41.0
  configFiles:
    Debug: Configs/Debug.xcconfig
    Release: Configs/Release.xcconfig
fileGroups:
  - App/Sources
  - App/Resources
targetTemplates:
  BaseAppTarget:
    platform: iOS
    deploymentTarget: '17.0'
    type: application
    configFiles:
      Debug: Configs/Debug.xcconfig
      Release: Configs/Release.xcconfig
packages:
  LibraryServiceLoader:
    path: Packages/Library/ServiceLoader
  LibraryThemeKit:
    path: Packages/Library/ThemeKit
  LibraryNetworking:
    path: Packages/Library/Networking
  DomainHealth:
    path: Packages/Domain/Health
  DomainAuth:
    path: Packages/Domain/DomainAuth
  DomainChat:
    path: Packages/Domain/DomainChat
  DomainOnboarding:
    path: Packages/Domain/Onboarding
  FeatureHealthKitApi:
    path: Packages/Feature/HealthKit/FeatureHealthKitApi
  FeatureHealthKitImpl:
    path: Packages/Feature/HealthKit/FeatureHealthKitImpl
  FeatureAccountApi:
    path: Packages/Feature/FeatureAccount/FeatureAccountApi
  FeatureAccountImpl:
    path: Packages/Feature/FeatureAccount/FeatureAccountImpl
  FeatureChatApi:
    path: Packages/Feature/FeatureChat/FeatureChatApi
  FeatureChatImpl:
    path: Packages/Feature/FeatureChat/FeatureChatImpl
  FeatureOnboardingApi:
    path: Packages/Feature/Onboarding/FeatureOnboardingApi
  FeatureOnboardingImpl:
    path: Packages/Feature/Onboarding/FeatureOnboardingImpl
targets:
  HealthBuddy:
    templates: [BaseAppTarget]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.high.HealthBuddy
      CODE_SIGN_ENTITLEMENTS: App/HealthBuddy.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_FILE: App/Resources/Info.plist
      GENERATE_INFOPLIST_FILE: NO
    sources:
      - path: App/Sources
      - path: App/Resources/Assets.xcassets
        buildPhase: resources
      - path: App/Resources/en.lproj
        buildPhase: resources
      - path: App/Resources/LaunchScreen.storyboard
        buildPhase: resources
    resources: []
    dependencies:
      - package: LibraryServiceLoader
        product: LibraryServiceLoader
      - package: LibraryThemeKit
        product: ThemeKit
      - package: LibraryNetworking
        product: LibraryNetworking
      - package: DomainHealth
        product: DomainHealth
      - package: DomainAuth
        product: DomainAuth
      - package: DomainChat
        product: DomainChat
      - package: DomainOnboarding
        product: DomainOnboarding
      - package: FeatureHealthKitApi
        product: FeatureHealthKitApi
      - package: FeatureHealthKitImpl
        product: FeatureHealthKitImpl
      - package: FeatureAccountApi
        product: FeatureAccountApi
      - package: FeatureAccountImpl
        product: FeatureAccountImpl
      - package: FeatureChatApi
        product: FeatureChatApi
      - package: FeatureChatImpl
        product: FeatureChatImpl
      - package: FeatureOnboardingApi
        product: FeatureOnboardingApi
      - package: FeatureOnboardingImpl
        product: FeatureOnboardingImpl
schemes:
  HealthBuddy:
    build:
      targets:
        HealthBuddy: all
    run:
      config: Debug
    archive:
      config: Release
